spring:
  profiles:
    include: docker # local

  datasource:
    url: jdbc:h2:mem:testdb
    driver: org.h2.Driver
    
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        #dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2: 
      client:
        registration:
          kakao:
            client-id: b8602ae10aac13940debe944bd503178
            client-secret: 4g2BHUeX9Uq9ZfnZuz4CctUSS1pI0XSF
            scope: 
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect_uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            
token:
  secret: ZXZlbnQtYm9hcmQtanNvbi13ZWItdG9rZW4tc2VjcmV0LWtleQ==
  expiry: 604800000

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace